import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentDatabaseUser } from "@/lib/databaseAuth";
import { getPrisma } from "@/lib/prisma";
const schema = z.object({ familyName: z.string().trim().max(120).optional(), primaryGuardianName: z.string().trim().min(2).max(120), primaryGuardianPhone: z.string().trim().min(5).max(30), primaryGuardianRelationship: z.string().trim().min(2).max(80), secondaryGuardianName: z.string().trim().max(120).optional(), secondaryGuardianPhone: z.string().trim().max(30).optional(), secondaryGuardianRelationship: z.string().trim().max(80).optional(), city: z.string().trim().min(2).max(80), address: z.string().trim().max(300).optional(), householdSize: z.number().int().positive().max(50).optional(), primaryOccupation: z.string().trim().max(120).optional(), incomeRange: z.enum(["BELOW_10000","INR_10000_20000","INR_20000_30000","INR_30000_50000","INR_50000_100000","ABOVE_100000","PREFER_NOT_TO_SAY"]), supportNotes: z.string().trim().max(1000).optional() });
async function allowed() { const u = await getCurrentDatabaseUser(); return u?.role === "ADMIN" ? u : null; }
export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { if (!await allowed()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const family = await getPrisma().family.findUnique({ where: { id: (await params).id }, include: { members: { include: { user: { select: { id: true, name: true, email: true, role: true, studentProfile: true } } } }, assistanceRequests: { orderBy: { createdAt: "desc" }, include: { student: { select: { id: true, name: true, email: true } } } } } }); if (!family) return NextResponse.json({ error: "Family not found" }, { status: 404 }); return NextResponse.json({ family }); }
export async function PATCH(req: Request, { params }: { params: Promise<{ id: string }> }) { if (!await allowed()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const parsed = schema.safeParse(await req.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid family details" }, { status: 400 }); try { return NextResponse.json({ family: await getPrisma().family.update({ where: { id: (await params).id }, data: parsed.data }) }); } catch { return NextResponse.json({ error: "Family not found" }, { status: 404 }); } }
export async function POST(req: Request, { params }: { params: Promise<{ id: string }> }) { const actor = await allowed(); if (!actor) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const body = await req.json().catch(() => null); const studentId = String(body?.studentId ?? ""); const relationship = String(body?.relationship ?? "CHILD").trim(); const prisma = getPrisma(); const student = await prisma.user.findFirst({ where: { id: studentId, role: "STUDENT" }, select: { id: true } }); if (!student) return NextResponse.json({ error: "Student not found" }, { status: 404 }); try { const member = await prisma.familyMember.create({ data: { familyId: (await params).id, userId: student.id, relationship } }); return NextResponse.json({ member }, { status: 201 }); } catch { return NextResponse.json({ error: "Student already belongs to a family or family not found" }, { status: 409 }); } }
export async function DELETE(req: Request, { params }: { params: Promise<{ id: string }> }) { if (!await allowed()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const {id}=await params; const url=new URL(req.url); const studentId=url.searchParams.get("studentId"); const prisma=getPrisma(); if(studentId){const membership=await prisma.familyMember.findFirst({where:{userId:studentId,familyId:id},select:{id:true}});if(!membership)return NextResponse.json({error:"Membership not found"},{status:404});await prisma.$transaction([prisma.familyMember.delete({where:{id:membership.id}}),prisma.studentProfile.updateMany({where:{userId:studentId,familyId:id},data:{familyId:null}})]);return NextResponse.json({ok:true,action:"unlinked"});} if(url.searchParams.get("family")==="true"){const family=await prisma.family.findUnique({where:{id},select:{_count:{select:{members:true,profiles:true,assistanceRequests:true}}}});if(!family)return NextResponse.json({error:"Family not found"},{status:404});if(Object.values(family._count).some(Boolean))return NextResponse.json({error:"Only empty families without assistance history can be deleted."},{status:409});await prisma.family.delete({where:{id}});return NextResponse.json({ok:true,action:"deleted"});} return NextResponse.json({ error: "studentId or family=true is required" }, { status: 400 }); }
