"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { useEffect, useState } from "react";

const interests = ["Quran", "Tajweed", "Seerah", "Fiqh", "Hadith", "Islamic History", "Arabic", "Other"];
const incomeOptions = [
  ["BELOW_10000", "Below ₹10,000"], ["INR_10000_20000", "₹10,000–₹20,000"],
  ["INR_20000_30000", "₹20,000–₹30,000"], ["INR_30000_50000", "₹30,000–₹50,000"],
  ["INR_50000_100000", "₹50,000–₹1,00,000"], ["ABOVE_100000", "Above ₹1,00,000"],
  ["PREFER_NOT_TO_SAY", "Prefer not to say"],
];
const grid = { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 14 } as const;
const fieldStyle = { display: "grid", gap: 7 } as const;

function Field({ label, value, onChange, type = "text", required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) {
  return <label style={fieldStyle}><span>{label}</span><input type={type} required={required} value={value} onChange={e => onChange(e.target.value)} /></label>;
}

export default function ProfilePage() {
  const [user, setUser] = useState<any>(null); const [form, setForm] = useState<any>({}); const [family, setFamily] = useState<any>({ incomeRange: "PREFER_NOT_TO_SAY" });
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/profile").then(r => r.json()).then(data => { if (!data.user) return setError(data.error || "Unable to load profile"); setUser(data.user); const profile = data.profile || { fullName: data.user.name || "" }; setForm({ ...profile, dateOfBirth: profile.dateOfBirth ? String(profile.dateOfBirth).slice(0, 10) : "" }); setFamily(profile.family || { incomeRange: "PREFER_NOT_TO_SAY" }); }).catch(() => setError("Unable to load profile")); }, []);
  const update = (key: string, value: unknown) => setForm((old: any) => ({ ...old, [key]: value }));
  const updateFamily = (key: string, value: unknown) => setFamily((old: any) => ({ ...old, [key]: value }));

  async function save(e: React.FormEvent) {
    e.preventDefault(); setError(""); setMessage("");
    const isStudent = user.role === "STUDENT";
    const familyHasData = isStudent && Object.entries(family).some(([key, value]) => key !== "incomeRange" && String(value ?? "").trim());
    if (familyHasData && (!family.primaryGuardianName?.trim() || !family.primaryGuardianPhone?.trim() || !family.primaryGuardianRelationship?.trim() || !family.city?.trim())) return setError("Primary guardian name, relationship, phone, and city are required when adding family details.");
    const studentPayload = { fullName: form.fullName, phone: form.phone, dateOfBirth: form.dateOfBirth, schoolOrCollege: form.schoolOrCollege, gradeOrClass: form.gradeOrClass, guardianName: form.guardianName, guardianPhone: form.guardianPhone, city: form.city, introducedBy: form.introducedBy, likesAboutSba: form.likesAboutSba, contributionInterest: form.contributionInterest, improvementSuggestion: form.improvementSuggestion, learningInterests: form.learningInterests, learningGoal: form.learningGoal, ...(familyHasData ? { family: { familyName: family.familyName, primaryGuardianName: family.primaryGuardianName, primaryGuardianPhone: family.primaryGuardianPhone, primaryGuardianRelationship: family.primaryGuardianRelationship, secondaryGuardianName: family.secondaryGuardianName, secondaryGuardianPhone: family.secondaryGuardianPhone, secondaryGuardianRelationship: family.secondaryGuardianRelationship, city: family.city, address: family.address, householdSize: family.householdSize ? Number(family.householdSize) : undefined, primaryOccupation: family.primaryOccupation, incomeRange: family.incomeRange || "PREFER_NOT_TO_SAY" } } : {}) };
    const teacherPayload = { fullName: form.fullName, phone: form.phone, city: form.city, profileImage: form.profileImage, qualifications: form.qualifications, teachingExperience: form.teachingExperience, subjects: form.subjects, languages: form.languages, shortBio: form.shortBio, availability: form.availability };
    setSaving(true); const response = await fetch("/api/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(isStudent ? studentPayload : teacherPayload) }); const data = await response.json(); setSaving(false);
    if (!response.ok) return setError(data.error || "Unable to save profile"); setForm((old: any) => ({ ...old, ...data.profile })); setMessage("Profile saved.");
  }

  if (!user) return <main className="interior-page"><div className="interior-shell"><section className="interior-panel"><p>{error || "Loading profile…"}</p></section></div></main>;
  if (user.role === "ADMIN") return <main className="interior-page"><div className="interior-shell"><Link href="/dashboard" className="site-btn-secondary">Back to dashboard</Link><section className="interior-panel" style={{ marginTop: 24 }}><h1>{user.name || "Administrator"}</h1><p>{user.email}</p></section></div></main>;
  const student = user.role === "STUDENT";
  return <main className="interior-page"><div className="interior-shell" style={{ maxWidth: 940 }}><Link href="/dashboard" className="site-btn-secondary">Back to dashboard</Link><header className="dashboard-intro"><div><div className="site-section-label">Your account</div><h1>{student ? "Student profile" : "Teacher profile"}</h1><p>Keep your SBA account information current.</p></div></header><form onSubmit={save} style={{ display: "grid", gap: 18 }}>
    <section className="interior-panel"><h2>Personal</h2><div style={grid}><Field label="Full name" required value={form.fullName || ""} onChange={v => update("fullName", v)} /><Field label="Phone" value={form.phone || ""} onChange={v => update("phone", v)} />{student && <Field label="Date of birth" type="date" value={form.dateOfBirth || ""} onChange={v => update("dateOfBirth", v)} />}<Field label="City" value={form.city || ""} onChange={v => update("city", v)} /></div><p style={{ color: "#566860" }}>Email: {user.email} (read-only)</p></section>
    {student ? <><section className="interior-panel"><h2>Education</h2><div style={grid}><Field label="School or college" value={form.schoolOrCollege || ""} onChange={v => update("schoolOrCollege", v)} /><Field label="Class / grade" value={form.gradeOrClass || ""} onChange={v => update("gradeOrClass", v)} /></div><label style={{ ...fieldStyle, marginTop: 14 }}><span>Learning interests</span><div style={{ display: "flex", flexWrap: "wrap", gap: 12 }}>{interests.map(option => <label key={option} style={{ display: "flex", gap: 6, alignItems: "center" }}><input type="checkbox" checked={(form.learningInterests || []).includes(option)} onChange={e => update("learningInterests", e.target.checked ? [...(form.learningInterests || []), option] : (form.learningInterests || []).filter((item: string) => item !== option))} />{option}</label>)}</div></label><label style={{ ...fieldStyle, marginTop: 14 }}><span>Learning goal</span><textarea rows={3} value={form.learningGoal || ""} onChange={e => update("learningGoal", e.target.value)} /></label></section>
      <section className="interior-panel"><div className="site-section-label">Private household information</div><h2>Family</h2><p>These details are visible only in authorized member workflows.</p><div style={grid}><Field label="Family name (optional)" value={family.familyName || ""} onChange={v => updateFamily("familyName", v)} /><Field label="Primary guardian name" value={family.primaryGuardianName || ""} onChange={v => updateFamily("primaryGuardianName", v)} /><Field label="Primary guardian relationship" value={family.primaryGuardianRelationship || ""} onChange={v => updateFamily("primaryGuardianRelationship", v)} /><Field label="Primary guardian phone" value={family.primaryGuardianPhone || ""} onChange={v => updateFamily("primaryGuardianPhone", v)} /><Field label="Secondary guardian name" value={family.secondaryGuardianName || ""} onChange={v => updateFamily("secondaryGuardianName", v)} /><Field label="Secondary guardian relationship" value={family.secondaryGuardianRelationship || ""} onChange={v => updateFamily("secondaryGuardianRelationship", v)} /><Field label="Secondary guardian phone" value={family.secondaryGuardianPhone || ""} onChange={v => updateFamily("secondaryGuardianPhone", v)} /><Field label="Family city" value={family.city || ""} onChange={v => updateFamily("city", v)} /><Field label="Address" value={family.address || ""} onChange={v => updateFamily("address", v)} /><Field label="Household size" type="number" value={family.householdSize?.toString() || ""} onChange={v => updateFamily("householdSize", v)} /><Field label="Primary occupation" value={family.primaryOccupation || ""} onChange={v => updateFamily("primaryOccupation", v)} /><label style={fieldStyle}><span>Monthly household income range</span><select value={family.incomeRange || "PREFER_NOT_TO_SAY"} onChange={e => updateFamily("incomeRange", e.target.value)}>{incomeOptions.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label></div></section>
      <section className="interior-panel"><h2>SBA Community</h2><div style={grid}><Field label="Who introduced you to SBA?" value={form.introducedBy || ""} onChange={v => update("introducedBy", v)} /></div>{[["likesAboutSba", "What do you like about SBA?"], ["contributionInterest", "How would you like to contribute?"], ["improvementSuggestion", "What could SBA improve?"]].map(([key, label]) => <label key={key} style={{ ...fieldStyle, marginTop: 14 }}><span>{label}</span><textarea rows={3} value={form[key] || ""} onChange={e => update(key, e.target.value)} /></label>)}</section><section className="interior-panel"><h2>Assistance</h2><p>Submit a private request or review your existing requests.</p><Link href="/assistance" className="site-btn-secondary">Open financial assistance</Link></section></> : <section className="interior-panel"><h2>Teaching profile</h2><div style={grid}>{[["qualifications", "Qualifications"], ["teachingExperience", "Teaching experience"], ["availability", "Availability"]].map(([key, label]) => <Field key={key} label={label} value={form[key] || ""} onChange={v => update(key, v)} />)}</div><label style={{ ...fieldStyle, marginTop: 14 }}><span>Short bio</span><textarea rows={4} value={form.shortBio || ""} onChange={e => update("shortBio", e.target.value)} /></label></section>}
    {error && <p role="alert" style={{ color: "#b42318" }}>{error}</p>}{message && <p role="status" style={{ color: "#1a6045" }}>{message}</p>}<button className="site-btn-primary" disabled={saving} type="submit">{saving ? "Saving…" : "Save changes"}</button>
  </form></div></main>;
}
