import { NextResponse } from "next/server";
import bcrypt from "bcrypt";
import { z } from "zod";
import { getCurrentDatabaseUser } from "@/lib/databaseAuth";
import { getPrisma } from "@/lib/prisma";

export async function GET(req: Request) {
  const user = await getCurrentDatabaseUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  if (user.role !== "ADMIN") return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  const query = new URL(req.url).searchParams.get("q")?.trim() ?? "";
  const students = await getPrisma().user.findMany({ where: { role: "STUDENT", ...(query ? { OR: [{ name: { contains: query, mode: "insensitive" } }, { email: { contains: query, mode: "insensitive" } }] } : {}) }, orderBy: { createdAt: "desc" }, take: 100, select: { id: true, name: true, email: true, createdAt: true, studentProfile: true, enrollments: { include: { course: { select: { id: true, title: true, classes: { select: { id: true, title: true, scheduledAt: true, status: true } } } } } } } });
  return NextResponse.json({ students });
}

const studentSchema = z.object({ id: z.string().optional(), name: z.string().trim().min(2).max(120), email: z.string().email().max(240), password: z.string().min(8).max(128).optional(), phone: z.string().trim().max(30).optional(), schoolOrCollege: z.string().trim().max(160).optional(), gradeOrClass: z.string().trim().max(80).optional(), city: z.string().trim().max(80).optional() });
async function requireAdmin() { const user = await getCurrentDatabaseUser(); return user?.role === "ADMIN" ? user : null; }

export async function POST(req: Request) { const actor = await requireAdmin(); if (!actor) return NextResponse.json({error:"Forbidden"},{status:403}); const parsed=studentSchema.safeParse(await req.json().catch(()=>null)); if(!parsed.success||!parsed.data.password)return NextResponse.json({error:"Valid name, email, and password of at least 8 characters are required"},{status:400}); const {password,...input}=parsed.data; const prisma=getPrisma(); if(await prisma.user.findUnique({where:{email:input.email.toLowerCase()},select:{id:true}}))return NextResponse.json({error:"Email already used"},{status:409}); const student=await prisma.user.create({data:{name:input.name,email:input.email.toLowerCase(),password:await bcrypt.hash(password,10),role:"STUDENT",studentProfile:{create:{fullName:input.name,phone:input.phone||null,schoolOrCollege:input.schoolOrCollege||null,gradeOrClass:input.gradeOrClass||null,city:input.city||null}}},select:{id:true,name:true,email:true,studentProfile:true}}); await prisma.adminNotification.create({data:{type:"STUDENT_CREATED",actorUserId:actor.id,title:"Student created",message:`${input.name} was added as a student.`,entityType:"user",entityId:student.id}}); return NextResponse.json({student},{status:201}); }

export async function PATCH(req: Request) { if(!await requireAdmin())return NextResponse.json({error:"Forbidden"},{status:403}); const parsed=studentSchema.safeParse(await req.json().catch(()=>null)); if(!parsed.success||!parsed.data.id)return NextResponse.json({error:"Invalid student details"},{status:400}); const {id,...input}=parsed.data; const prisma=getPrisma(); const existing=await prisma.user.findFirst({where:{id,role:"STUDENT"},select:{id:true}}); if(!existing)return NextResponse.json({error:"Student not found"},{status:404}); try{const student=await prisma.user.update({where:{id},data:{name:input.name,email:input.email.toLowerCase(),studentProfile:{upsert:{create:{fullName:input.name,phone:input.phone||null,schoolOrCollege:input.schoolOrCollege||null,gradeOrClass:input.gradeOrClass||null,city:input.city||null},update:{fullName:input.name,phone:input.phone||null,schoolOrCollege:input.schoolOrCollege||null,gradeOrClass:input.gradeOrClass||null,city:input.city||null}}}},select:{id:true,name:true,email:true,studentProfile:true}});return NextResponse.json({student});}catch{return NextResponse.json({error:"Email already used"},{status:409});} }

export async function DELETE(req: Request) { if(!await requireAdmin())return NextResponse.json({error:"Forbidden"},{status:403}); const id=new URL(req.url).searchParams.get("id"); if(!id)return NextResponse.json({error:"id is required"},{status:400}); const prisma=getPrisma(); const student=await prisma.user.findFirst({where:{id,role:"STUDENT"},select:{id:true,_count:{select:{enrollments:true,classAttendances:true,questionsAsked:true,assistanceRequests:true,studentTransactions:true}}}}); if(!student)return NextResponse.json({error:"Student not found"},{status:404}); const history=Object.values(student._count).reduce((sum,value)=>sum+value,0); if(history)return NextResponse.json({error:"This student has learning or financial history and cannot be deleted. Preserve the account record."},{status:409}); await prisma.user.delete({where:{id}}); return NextResponse.json({ok:true}); }
