/* eslint-disable @typescript-eslint/no-unused-vars */
import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentDatabaseUser } from "@/lib/databaseAuth";
import { getPrisma } from "@/lib/prisma";
const schema = z.object({ id: z.string().optional(), type: z.enum(["INCOME", "EXPENSE"]), category: z.string().trim().min(2).max(80), amount: z.number().int().positive(), transactionDate: z.string().datetime(), description: z.string().trim().min(2).max(500), reference: z.string().trim().max(160).nullable().optional() });
async function admin() { const user = await getCurrentDatabaseUser(); return user?.role === "ADMIN" ? user : null; }
export async function GET(req: Request) { if (!await admin()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const p = new URL(req.url).searchParams; const type = p.get("type"); const category = p.get("category"); const q = p.get("q")?.trim(); const from = p.get("from"); const to = p.get("to"); const transactions = await getPrisma().financeTransaction.findMany({ where: { ...(type === "INCOME" || type === "EXPENSE" ? { type } : {}), ...(category ? { category } : {}), ...(q ? { OR: [{ description: { contains: q, mode: "insensitive" } }, { reference: { contains: q, mode: "insensitive" } }] } : {}), ...(from || to ? { transactionDate: { ...(from ? { gte: new Date(from) } : {}), ...(to ? { lte: new Date(to) } : {}) } } : {}) }, orderBy: { transactionDate: "desc" } }); return NextResponse.json({ transactions }); }
export async function POST(req: Request) { const actor = await admin(); if (!actor) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const parsed = schema.safeParse(await req.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid transaction" }, { status: 400 }); const { id: _, transactionDate, ...data } = parsed.data; const transaction = await getPrisma().financeTransaction.create({ data: { ...data, transactionDate: new Date(transactionDate), createdById: actor.id } }); return NextResponse.json({ transaction }, { status: 201 }); }
export async function PATCH(req: Request) { if (!await admin()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const parsed = schema.safeParse(await req.json().catch(() => null)); if (!parsed.success || !parsed.data.id) return NextResponse.json({ error: "Invalid transaction" }, { status: 400 }); const { id, transactionDate, ...data } = parsed.data; try { return NextResponse.json({ transaction: await getPrisma().financeTransaction.update({ where: { id }, data: { ...data, transactionDate: new Date(transactionDate) } }) }); } catch { return NextResponse.json({ error: "Transaction not found" }, { status: 404 }); } }
export async function DELETE(req: Request) { if (!await admin()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const id = new URL(req.url).searchParams.get("id"); if (!id) return NextResponse.json({ error: "id is required" }, { status: 400 }); try { await getPrisma().financeTransaction.delete({ where: { id } }); return NextResponse.json({ ok: true }); } catch { return NextResponse.json({ error: "Transaction not found" }, { status: 404 }); } }
