"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useState } from "react";
import Link from "next/link";
import { Pencil, Plus, Trash2, UserMinus, UserPlus } from "lucide-react";
import { SbaConfirmDialog, SbaDataTable, SbaEmptyState, SbaErrorState, SbaLoadingState, SbaPageHeader, SbaSearch } from "@/app/components/sba/SbaUi";

const blank={name:"",email:"",password:"",phone:"",schoolOrCollege:"",gradeOrClass:"",city:""};
export default function StudentsPage(){const[q,setQ]=useState("");const[students,setStudents]=useState<any[]>([]);const[courses,setCourses]=useState<any[]>([]);const[form,setForm]=useState<any>(blank);const[editing,setEditing]=useState<any>(null);const[confirm,setConfirm]=useState<any>(null);const[unenrollTarget,setUnenrollTarget]=useState<any>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
const load=()=>{setLoading(true);Promise.all([fetch(`/api/admin/students?q=${encodeURIComponent(q)}`).then(r=>r.json()),fetch("/api/education/courses").then(r=>r.json())]).then(([a,b])=>{if(a.error)throw new Error(a.error);setStudents(a.students||[]);setCourses(b.courses||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
// Search is deliberately debounced and reloaded only when the query changes.
// eslint-disable-next-line react-hooks/exhaustive-deps
useEffect(()=>{const t=setTimeout(load,180);return()=>clearTimeout(t)},[q]);
function open(item?:any){setEditing(item||{});setForm(item?{id:item.id,name:item.studentProfile?.fullName||item.name||"",email:item.email,phone:item.studentProfile?.phone||"",schoolOrCollege:item.studentProfile?.schoolOrCollege||"",gradeOrClass:item.studentProfile?.gradeOrClass||"",city:item.studentProfile?.city||"",password:""}:blank);setError("");setMessage("")}
async function save(e:React.FormEvent){e.preventDefault();setBusy(true);const {password,...editable}=form;const payload=form.id?editable:{...editable,password};const r=await fetch("/api/admin/students",{method:form.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();setBusy(false);if(!r.ok)return setError(d.error||"Unable to save student");setEditing(null);setMessage(form.id?"Student updated.":"Student created.");load()}
async function enroll(studentId:string,courseId:string){if(!courseId)return;const r=await fetch("/api/education/enrollments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({studentId,courseId})});const d=await r.json();setMessage(r.ok?"Student enrolled.":d.error||"Unable to enroll");if(r.ok)load()}
async function unenroll(){if(!unenrollTarget)return;setBusy(true);const r=await fetch("/api/education/enrollments",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({studentId:unenrollTarget.studentId,courseId:unenrollTarget.courseId})});const d=await r.json();setBusy(false);setUnenrollTarget(null);setMessage(r.ok?"Enrollment removed.":d.error||"Unable to remove enrollment");if(r.ok)load()}
async function remove(){if(!confirm)return;setBusy(true);const r=await fetch(`/api/admin/students?id=${confirm.id}`,{method:"DELETE"});const d=await r.json();setBusy(false);setConfirm(null);setMessage(r.ok?"Student deleted.":d.error||"Unable to delete");if(r.ok)load()}
return <main className="interior-page"><div className="interior-shell"><SbaPageHeader eyebrow="People" title="Students" description="Manage learner profiles, course access, and family context without exposing credentials." actions={<button className="site-btn-primary" onClick={()=>open()}><Plus size={16}/> Add student</button>}/>{message&&<p role="status">{message}</p>}<div className="sba-toolbar"><SbaSearch value={q} onChange={setQ} placeholder="Search students by name or email"/><Link href="/admin/families" className="site-btn-secondary">Manage families</Link></div>{error&&!editing&&<SbaErrorState message={error}/>} {loading?<SbaLoadingState label="Loading students…"/>:students.length===0?<SbaEmptyState title="No students found" description="Add the first student or adjust your search." action={<button className="site-btn-primary" onClick={()=>open()}>Add student</button>}/>:<SbaDataTable headers={["Student","Education","Courses","Joined","Actions"]}>{students.map(s=><tr key={s.id}><td data-label="Student"><strong>{s.studentProfile?.fullName||s.name||"Unnamed student"}</strong><small>{s.email} · {s.studentProfile?.phone||"No phone"}</small></td><td data-label="Education">{s.studentProfile?.schoolOrCollege||"Not added"}<small>{s.studentProfile?.gradeOrClass||"No grade"}</small></td><td data-label="Courses"><strong>{s.enrollments.length}</strong><div style={{display:"grid",gap:5,margin:"6px 0"}}>{s.enrollments.map((enrollment:any)=><span key={enrollment.course.id} className="sba-status-badge" style={{justifyContent:"space-between"}}>{enrollment.course.title}<button type="button" className="sba-icon-button" aria-label={`Remove ${s.name||s.email} from ${enrollment.course.title}`} onClick={()=>setUnenrollTarget({studentId:s.id,studentName:s.name||s.email,courseId:enrollment.course.id,courseTitle:enrollment.course.title})}><UserMinus size={14}/></button></span>)}</div><select aria-label={`Enroll ${s.name||s.email} in course`} defaultValue="" onChange={e=>{enroll(s.id,e.target.value);e.target.value=""}}><option value="">Enroll…</option>{courses.filter(c=>!s.enrollments.some((x:any)=>x.course.id===c.id)).map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></td><td data-label="Joined">{new Date(s.createdAt).toLocaleDateString()}</td><td data-label="Actions"><div className="sba-row-actions"><button className="sba-icon-button" aria-label={`Edit ${s.name||s.email}`} onClick={()=>open(s)}><Pencil size={16}/></button><Link className="sba-icon-button" aria-label="Manage family" href="/admin/families"><UserPlus size={16}/></Link><button className="sba-icon-button" aria-label={`Delete ${s.name||s.email}`} onClick={()=>setConfirm(s)}><Trash2 size={16}/></button></div></td></tr>)}</SbaDataTable>}
{editing&&<div className="sba-dialog-backdrop" onMouseDown={()=>setEditing(null)}><form className="sba-dialog" onSubmit={save} onMouseDown={e=>e.stopPropagation()}><span className="sba-eyebrow">{form.id?"Edit learner":"New learner"}</span><h2>{form.id?"Update student":"Add student"}</h2><div className="sba-form-grid" style={{marginTop:18}}>{[["name","Full name"],["email","Email"],["phone","Phone"],["schoolOrCollege","School / college"],["gradeOrClass","Class / grade"],["city","City"]].map(([key,label])=><label key={key}><span>{label}</span><input required={key==="name"||key==="email"} type={key==="email"?"email":"text"} value={form[key]||""} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}{!form.id&&<label className="is-wide"><span>Temporary password</span><input required minLength={8} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>}</div>{error&&<p role="alert">{error}</p>}<div className="sba-dialog-actions"><button type="button" className="site-btn-secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="site-btn-primary" disabled={busy}>{busy?"Saving…":"Save student"}</button></div></form></div>}<SbaConfirmDialog open={!!confirm} title={`Delete ${confirm?.name||confirm?.email||"student"}?`} description="Deletion is allowed only when no enrollment, attendance, assistance, question, or financial history exists." confirmLabel="Delete student" busy={busy} onCancel={()=>setConfirm(null)} onConfirm={remove}/><SbaConfirmDialog open={!!unenrollTarget} title={`Remove ${unenrollTarget?.studentName||"student"} from ${unenrollTarget?.courseTitle||"course"}?`} description="The student will lose course access. Existing class and attendance history is preserved." confirmLabel="Remove enrollment" busy={busy} onCancel={()=>setUnenrollTarget(null)} onConfirm={unenroll}/></div></main>}
