"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { Trash2, UserMinus } from "lucide-react";
import { SbaConfirmDialog, SbaEmptyState, SbaLoadingState, SbaPageHeader, SbaStatusBadge } from "@/app/components/sba/SbaUi";

const fields = [["familyName", "Family name"], ["primaryGuardianName", "Primary guardian"], ["primaryGuardianPhone", "Primary guardian phone"], ["primaryGuardianRelationship", "Primary guardian relationship"], ["secondaryGuardianName", "Secondary guardian"], ["secondaryGuardianPhone", "Secondary guardian phone"], ["secondaryGuardianRelationship", "Secondary guardian relationship"], ["city", "City"], ["address", "Address"], ["householdSize", "Household size"], ["primaryOccupation", "Primary occupation"], ["supportNotes", "Private support notes"]];
const income = [["BELOW_10000", "Below ₹10,000"], ["INR_10000_20000", "₹10,000–₹20,000"], ["INR_20000_30000", "₹20,000–₹30,000"], ["INR_30000_50000", "₹30,000–₹50,000"], ["INR_50000_100000", "₹50,000–₹1,00,000"], ["ABOVE_100000", "Above ₹1,00,000"], ["PREFER_NOT_TO_SAY", "Prefer not to say"]];

export default function FamilyDetail({ params }: { params: Promise<{ id: string }> }) {
  const router = useRouter();
  const [id, setId] = useState(""); const [family, setFamily] = useState<any>(null); const [form, setForm] = useState<any>({}); const [students, setStudents] = useState<any[]>([]); const [studentId, setStudentId] = useState(""); const [confirm, setConfirm] = useState<any>(null); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { params.then(async ({ id: nextId }) => { setId(nextId); const [familyResponse, studentResponse] = await Promise.all([fetch(`/api/admin/families/${nextId}`), fetch("/api/admin/students")]); const familyData = await familyResponse.json(); const studentData = await studentResponse.json(); if (familyData.family) { setFamily(familyData.family); setForm(familyData.family); } else setError(familyData.error || "Unable to load family"); setStudents(studentData.students || []); }); }, [params]);
  async function save(event: React.FormEvent) { event.preventDefault(); setBusy(true); const response = await fetch(`/api/admin/families/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, householdSize: form.householdSize ? Number(form.householdSize) : undefined }) }); const data = await response.json(); setBusy(false); if (!response.ok) return setError(data.error); setFamily(data.family); setMessage("Family details saved."); }
  async function link() { if (!studentId) return; setBusy(true); const response = await fetch(`/api/admin/families/${id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ studentId }) }); const data = await response.json(); setBusy(false); if (!response.ok) return setError(data.error); setFamily({ ...family, members: [...family.members, data.member] }); setStudentId(""); setMessage("Student linked to family."); }
  async function remove() { if (!confirm) return; setBusy(true); const url = confirm.type === "family" ? `/api/admin/families/${id}?family=true` : `/api/admin/families/${id}?studentId=${encodeURIComponent(confirm.userId)}`; const response = await fetch(url, { method: "DELETE" }); const data = await response.json(); setBusy(false); setConfirm(null); if (!response.ok) return setError(data.error); if (data.action === "deleted") return router.push("/admin/families"); setFamily({ ...family, members: family.members.filter((member: any) => member.userId !== confirm.userId) }); setMessage("Student unlinked; their account and history were preserved."); }

  if (!family) return <main className="interior-page"><div className="interior-shell">{error ? <p role="alert">{error}</p> : <SbaLoadingState label="Loading family…" />}</div></main>;
  const availableStudents = students.filter((student) => !family.members.some((member: any) => member.userId === student.id));
  return <main className="interior-page"><div className="interior-shell"><SbaPageHeader eyebrow="Household" title={family.familyName || "Family details"} description="Guardian, household, membership, and assistance context in one protected record." actions={<><Link href="/admin/families" className="site-btn-secondary">All families</Link><button type="button" className="site-btn-secondary" onClick={() => setConfirm({ type: "family" })}><Trash2 size={16} /> Delete empty family</button></>} />{message && <p role="status">{message}</p>}{error && <p role="alert">{error}</p>}
    <form onSubmit={save} className="sba-panel"><div className="sba-form-grid">{fields.map(([key, label]) => <label key={key} className={key === "address" || key === "supportNotes" ? "is-wide" : undefined}><span>{label}</span>{key === "supportNotes" ? <textarea rows={4} maxLength={2000} value={form[key] ?? ""} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /> : <input value={form[key] ?? ""} type={key === "householdSize" ? "number" : "text"} onChange={(event) => setForm({ ...form, [key]: event.target.value })} />}</label>)}<label><span>Monthly household income</span><select value={form.incomeRange || "PREFER_NOT_TO_SAY"} onChange={(event) => setForm({ ...form, incomeRange: event.target.value })}>{income.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div><div className="sba-dialog-actions"><button className="site-btn-primary" disabled={busy}>{busy ? "Saving…" : "Save family"}</button></div></form>
    <section className="sba-panel" style={{ marginTop: 18 }}><h2>Members</h2><div style={{ display: "grid", gap: 8, marginTop: 14 }}>{family.members.length ? family.members.map((member: any) => <div key={member.id} className="sba-toolbar"><div><strong>{member.user.name || member.user.email}</strong><p>{member.relationship}</p></div><button type="button" className="sba-icon-button" aria-label={`Unlink ${member.user.name || member.user.email}`} onClick={() => setConfirm({ type: "member", userId: member.userId, name: member.user.name || member.user.email })}><UserMinus size={16} /></button></div>) : <SbaEmptyState title="No family members linked" />}</div><div className="sba-toolbar" style={{ marginTop: 14 }}><select aria-label="Existing student" value={studentId} onChange={(event) => setStudentId(event.target.value)}><option value="">Select an existing student</option>{availableStudents.map((student) => <option key={student.id} value={student.id}>{student.name || student.email} · {student.email}</option>)}</select><button type="button" className="site-btn-secondary" disabled={!studentId || busy} onClick={link}>Link student</button></div></section>
    <section className="sba-panel" style={{ marginTop: 18 }}><h2>Assistance</h2><div style={{ display: "grid", gap: 8, marginTop: 14 }}>{family.assistanceRequests.length ? family.assistanceRequests.map((request: any) => <div className="sba-toolbar" key={request.id}><div><strong>{request.student.name || request.student.email}</strong><p>{request.assistanceType.replaceAll("_", " ")}</p></div><SbaStatusBadge value={request.status} /></div>) : <SbaEmptyState title="No assistance requests" />}</div></section>
    <SbaConfirmDialog open={!!confirm} title={confirm?.type === "family" ? "Delete this family?" : `Unlink ${confirm?.name || "student"}?`} description={confirm?.type === "family" ? "Only a family with no members, linked profiles, or assistance history can be deleted." : "The student account, enrollment, attendance, and assistance history remain intact."} confirmLabel={confirm?.type === "family" ? "Delete family" : "Unlink student"} busy={busy} onCancel={() => setConfirm(null)} onConfirm={remove} />
  </div></main>;
}
