"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { useEffect, useState } from "react";

export default function FamilyDetail({ params }: { params: Promise<{ id: string }> }) {
  const [id, setId] = useState(""); const [family, setFamily] = useState<any>(null); const [form, setForm] = useState<any>({}); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [studentId, setStudentId] = useState("");
  useEffect(() => { params.then(({ id: nextId }) => { setId(nextId); fetch(`/api/admin/families/${nextId}`).then(r => r.json()).then(d => d.family ? (setFamily(d.family), setForm(d.family)) : setError(d.error || "Unable to load family")); }); }, [params]);
  async function save(e: React.FormEvent) { e.preventDefault(); const r = await fetch(`/api/admin/families/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, householdSize: form.householdSize ? Number(form.householdSize) : undefined }) }); const d = await r.json(); if (!r.ok) return setError(d.error); setFamily(d.family); setMessage("Family saved."); }
  async function link() { const r = await fetch(`/api/admin/families/${id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ studentId }) }); const d = await r.json(); if (!r.ok) return setError(d.error); setFamily({ ...family, members: [...family.members, d.member] }); setStudentId(""); }
  async function unlink(userId: string) { const r = await fetch(`/api/admin/families/${id}?studentId=${encodeURIComponent(userId)}`, { method: "DELETE" }); if (r.ok) setFamily({ ...family, members: family.members.filter((m: any) => m.userId !== userId) }); }
  if (!family) return <main className="interior-page"><div className="interior-shell"><Link href="/admin/families" className="site-btn-secondary">Families</Link><p>{error || "Loading family…"}</p></div></main>;
  return <main className="interior-page"><div className="interior-shell"><Link href="/admin/families" className="site-btn-secondary">Families</Link><h1 style={{ marginTop: 24 }}>{family.familyName || "Family"}</h1><form onSubmit={save} className="interior-panel" style={{ display: "grid", gap: 12, marginTop: 18 }}>{["familyName", "primaryGuardianName", "primaryGuardianPhone", "primaryGuardianRelationship", "secondaryGuardianName", "secondaryGuardianPhone", "secondaryGuardianRelationship", "city", "address", "householdSize", "primaryOccupation", "incomeRange", "supportNotes"].map(key => <label key={key} style={{ display: "grid", gap: 6 }}><span>{key}</span>{key === "incomeRange" ? <select value={form[key] || "PREFER_NOT_TO_SAY"} onChange={e => setForm({ ...form, [key]: e.target.value })}>{["BELOW_10000", "INR_10000_20000", "INR_20000_30000", "INR_30000_50000", "INR_50000_100000", "ABOVE_100000", "PREFER_NOT_TO_SAY"].map(v => <option key={v}>{v}</option>)}</select> : <input value={form[key] ?? ""} type={key === "householdSize" ? "number" : "text"} onChange={e => setForm({ ...form, [key]: e.target.value })} />}</label>)}{error && <p role="alert">{error}</p>}{message && <p role="status">{message}</p>}<button className="site-btn-primary">Save family</button></form><section className="interior-panel" style={{ marginTop: 18 }}><h2>Members</h2>{family.members.map((m: any) => <p key={m.id}>{m.user.name || m.user.email} · {m.relationship} <button type="button" className="site-btn-secondary" onClick={() => unlink(m.userId)}>Unlink</button></p>)}<div style={{ display: "flex", gap: 8 }}><input aria-label="Student ID" placeholder="Existing student ID" value={studentId} onChange={e => setStudentId(e.target.value)} /><button type="button" className="site-btn-secondary" onClick={link}>Link student</button></div></section><section className="interior-panel" style={{ marginTop: 18 }}><h2>Assistance</h2>{family.assistanceRequests.length ? family.assistanceRequests.map((r: any) => <p key={r.id}>{r.student.name || r.student.email} · {r.assistanceType} · {r.status}</p>) : <p>No assistance requests.</p>}</section></div></main>;
}
