import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentDatabaseUser } from "@/lib/databaseAuth";
import { getPrisma } from "@/lib/prisma";

const familySchema = z.object({ familyName: z.string().trim().max(120).optional(), primaryGuardianName: z.string().trim().min(2).max(120), primaryGuardianPhone: z.string().trim().min(5).max(30), primaryGuardianRelationship: z.string().trim().min(2).max(80), secondaryGuardianName: z.string().trim().max(120).optional(), secondaryGuardianPhone: z.string().trim().max(30).optional(), secondaryGuardianRelationship: z.string().trim().max(80).optional(), city: z.string().trim().min(2).max(80), address: z.string().trim().max(300).optional(), householdSize: z.number().int().positive().max(50).optional(), primaryOccupation: z.string().trim().max(120).optional(), incomeRange: z.enum(["BELOW_10000","INR_10000_20000","INR_20000_30000","INR_30000_50000","INR_50000_100000","ABOVE_100000","PREFER_NOT_TO_SAY"]), supportNotes: z.string().trim().max(1000).optional() });
async function admin() { const u = await getCurrentDatabaseUser(); return u?.role === "ADMIN" ? u : null; }
export async function GET(req: Request) { if (!await admin()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const q = new URL(req.url).searchParams.get("q")?.trim() ?? ""; const families = await getPrisma().family.findMany({ where: q ? { OR: [{ familyName: { contains: q, mode: "insensitive" } }, { primaryGuardianName: { contains: q, mode: "insensitive" } }, { primaryGuardianPhone: { contains: q } }] } : undefined, orderBy: { updatedAt: "desc" }, include: { members: { include: { user: { select: { id: true, name: true, email: true, role: true } } } }, _count: { select: { assistanceRequests: true } } } }); return NextResponse.json({ families }); }
export async function POST(req: Request) { const actor = await admin(); if (!actor) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const parsed = familySchema.safeParse(await req.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid family details" }, { status: 400 }); const family = await getPrisma().family.create({ data: parsed.data }); return NextResponse.json({ family }, { status: 201 }); }
