/* eslint-disable @typescript-eslint/no-unused-vars */
import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentDatabaseUser } from "@/lib/databaseAuth";
import { getPrisma } from "@/lib/prisma";

const salarySchema = z.object({ id: z.string().optional(), teacherId: z.string().min(1), month: z.number().int().min(1).max(12), year: z.number().int().min(2020).max(2100), baseAmount: z.number().int().nonnegative(), bonusAmount: z.number().int().nonnegative().default(0), deductionAmount: z.number().int().nonnegative().default(0), status: z.enum(["PENDING", "PARTIALLY_PAID", "PAID", "ON_HOLD"]).default("PENDING"), paymentReference: z.string().trim().max(160).nullable().optional(), notes: z.string().trim().max(1000).nullable().optional() });
async function requireAdmin() { const user = await getCurrentDatabaseUser(); return user?.role === "ADMIN" ? user : null; }
export async function GET(req: Request) { if (!await requireAdmin()) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const p = new URL(req.url).searchParams; const teacherId = p.get("teacherId") || undefined; const month = p.get("month"); const year = p.get("year"); const q = p.get("q")?.trim(); const salaries = await getPrisma().teacherSalaryPayment.findMany({ where: { ...(teacherId ? { teacherId } : {}), ...(month ? { month: Number(month) } : {}), ...(year ? { year: Number(year) } : {}), ...(q ? { teacher: { OR: [{ name: { contains: q, mode: "insensitive" } }, { email: { contains: q, mode: "insensitive" } }] } } : {}) }, orderBy: [{ year: "desc" }, { month: "desc" }], include: { teacher: { select: { id: true, name: true, email: true } } } }); return NextResponse.json({ salaries }); }
export async function POST(req: Request) { const actor = await requireAdmin(); if (!actor) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const parsed = salarySchema.safeParse(await req.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid salary details" }, { status: 400 }); const { id: _, ...data } = parsed.data; const teacher = await getPrisma().user.findFirst({ where: { id: data.teacherId, role: "TEACHER" }, select: { id: true } }); if (!teacher) return NextResponse.json({ error: "Teacher not found" }, { status: 404 }); const finalAmount = data.baseAmount + data.bonusAmount - data.deductionAmount; if (finalAmount < 0) return NextResponse.json({ error: "Deduction cannot exceed base plus bonus" }, { status: 400 }); try { const salary = await getPrisma().teacherSalaryPayment.create({ data: { ...data, finalAmount, createdById: actor.id, paidAt: data.status === "PAID" ? new Date() : null } }); return NextResponse.json({ salary }, { status: 201 }); } catch { return NextResponse.json({ error: "Salary already exists for this teacher and period" }, { status: 409 }); } }
export async function PATCH(req: Request) { const actor = await requireAdmin(); if (!actor) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const parsed = salarySchema.safeParse(await req.json().catch(() => null)); if (!parsed.success || !parsed.data.id) return NextResponse.json({ error: "Invalid salary details" }, { status: 400 }); const { id, ...data } = parsed.data; const teacher = await getPrisma().user.findFirst({ where: { id: data.teacherId, role: "TEACHER" }, select: { id: true } }); if (!teacher) return NextResponse.json({ error: "Teacher not found" }, { status: 404 }); const finalAmount = data.baseAmount + data.bonusAmount - data.deductionAmount; if (finalAmount < 0) return NextResponse.json({ error: "Deduction cannot exceed base plus bonus" }, { status: 400 }); try { const salary = await getPrisma().teacherSalaryPayment.update({ where: { id }, data: { ...data, finalAmount, paidAt: data.status === "PAID" ? new Date() : null } }); return NextResponse.json({ salary }); } catch { return NextResponse.json({ error: "Salary not found or duplicate period" }, { status: 409 }); } }
